### ISSUE TITLE
关于数据集的下载链接：您好关于Flickr和Mashup我在您论文中并没有找到对应的下载链接，可以提供一下吗？

### ISSUE THREAD

**Issue by JialongWang1224** [llan-ml/MetaTNE#1]
在dataset的readme中说有在论文中给链接，但是我下载到的论文版本好像并没有提供数据集的链接，可以麻烦您提供一下吗？不知道在哪里能下载到

**Comment by JialongWang1224** [comment]
socialcomputing asu站点已经关闭，是否又其他链接可以下载同样的数据集合呢

**Comment by llan-ml** [comment]
@JialongWang1224 You can download the dataset from [this link](http://zhang18f.myweb.cs.uwindsor.ca/datasets/).

**Comment by sunfeng90** [comment]
Cannot download the same files like u from the this link(http://zhang18f.myweb.cs.uwindsor.ca/datasets/).

I can only get edges.csv and group-edges.csv and don't find groups.csv and nodes.csv.

Please share the original files u used by BadiDu disk and Google Disk.

Thanks a lot.
